name: gimp_ubuntu
description: Install GIMP image editor on Ubuntu

steps:
  - name: install_gimp
    script: |
      log_verbose "ðŸ“¦ Installing..."
      sudo apt update -y
      sudo apt install -y gimp
      echo "âœ… GIMP installed!"
