name: vlc_ubuntu
description: Install VLC media player on Ubuntu

steps:
  - name: install_vlc
    script: |
      log_verbose "ðŸ“¦ Installing..."
      sudo apt update -y
      sudo apt install -y vlc
      echo "âœ… VLC installed!"
