name: libreoffice_ubuntu
description: Install LibreOffice suite on Ubuntu

steps:
  - name: install_libreoffice
    script: |
      log_verbose "ðŸ“¦ Installing..."
      sudo apt update -y
      sudo apt install -y libreoffice
      echo "âœ… LibreOffice installed!"
